### ISSUE TITLE
Fatal Error if webpack is not initialized

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/booka-issues#210]
Without initialized app scripts the system expects a string from meta.json, receives a bool (non existent and excepts unceremoniously:

```
[16-May-2020 15:21:22 Asia/Bangkok] PHP Warning:  file_get_contents(/home/hdtravel/hdtravel.inkohsamui.com/public/theme/assets/scripts/meta.json): failed to open stream: No such file or directory in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:22 Asia/Bangkok] PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php:426
Stack trace:
#0 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(426): json_decode(false)
#1 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(290): Booka\Page\Page->prepare()
#2 /home/hdtravel/hdtravel.inkohsamui.com/public/index.php(44): Booka\Page\Page->display('/home/hdtravel/...')
#3 {main}
  thrown in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:23 Asia/Bangkok] PHP Warning:  file_get_contents(/home/hdtravel/hdtravel.inkohsamui.com/public/theme/assets/scripts/meta.json): failed to open stream: No such file or directory in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:23 Asia/Bangkok] PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php:426
Stack trace:
#0 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(426): json_decode(false)
#1 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(290): Booka\Page\Page->prepare()
#2 /home/hdtravel/hdtravel.inkohsamui.com/public/index.php(44): Booka\Page\Page->display('/home/hdtravel/...')
#3 {main}
  thrown in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:23 Asia/Bangkok] PHP Warning:  file_get_contents(/home/hdtravel/hdtravel.inkohsamui.com/public/theme/assets/scripts/meta.json): failed to open stream: No such file or directory in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:23 Asia/Bangkok] PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php:426
Stack trace:
#0 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(426): json_decode(false)
#1 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(290): Booka\Page\Page->prepare()
#2 /home/hdtravel/hdtravel.inkohsamui.com/public/index.php(44): Booka\Page\Page->display('/home/hdtravel/...')
#3 {main}
  thrown in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:24 Asia/Bangkok] PHP Warning:  file_get_contents(/home/hdtravel/hdtravel.inkohsamui.com/public/theme/assets/scripts/meta.json): failed to open stream: No such file or directory in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:24 Asia/Bangkok] PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php:426
Stack trace:
#0 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(426): json_decode(false)
#1 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(290): Booka\Page\Page->prepare()
#2 /home/hdtravel/hdtravel.inkohsamui.com/public/index.php(44): Booka\Page\Page->display('/home/hdtravel/...')
#3 {main}
  thrown in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:25 Asia/Bangkok] PHP Warning:  file_get_contents(/home/hdtravel/hdtravel.inkohsamui.com/public/theme/assets/scripts/meta.json): failed to open stream: No such file or directory in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
[16-May-2020 15:21:25 Asia/Bangkok] PHP Fatal error:  Uncaught TypeError: json_decode() expects parameter 1 to be string, bool given in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php:426
Stack trace:
#0 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(426): json_decode(false)
#1 /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php(290): Booka\Page\Page->prepare()
#2 /home/hdtravel/hdtravel.inkohsamui.com/public/index.php(44): Booka\Page\Page->display('/home/hdtravel/...')
#3 {main}
  thrown in /home/hdtravel/hdtravel.inkohsamui.com/src/Booka/Page/Page.php on line 426
```

**Comment by davidsneighbour** [comment]
should result in error page with info to debug.
